title: Bladimir Salazar
email: blax360.com@gmail.com
description: Director · Creator · Showrunner
baseurl: ""
url: "https://blax360.com"
branch: gh-pages

markdown: kramdown
plugins:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/