title: Bladimir Salazar - Creador Multimedia
email: blax360.com@gmail.com
description: >- # La descripción del sitio
  Creando historias, frame a frame.
baseurl: "https://blax360.github.io/blax360.com/" # La URL base para el despliegue (puedes dejarla vacía para entorno local)
url: "https://blax360.github.io/blax360.com/" # La URL de tu sitio web
twitter_username: blax360
github_username: blax360

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Excluir del procesamiento
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/